version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/themes/material/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/examples/material-demo/"
    schedule:
      interval: "monthly"
