name = "cloudflare-hono-sample"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-hono-sample"
database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
migrations_dir = "prisma/migrations/20240928175921_create_tables"

# [ai]
# binding = "AI"